### PR TITLE
add-filters-and-styles;

### PR DESCRIPTION
**Pull request by netsi**
- add filters
    - add style to match the iframe
    - allow users to pick custom primary color via parameters

### CODE REVIEW

**Comment by obiPlabon** [comment]
Wow, great work man.

I'll check and merge asap.

**Comment by wernerglinka** [comment]
What is the status of this PR?

**Comment by netsi** [comment]
@wernerglinka there is a fork of this repo,
https://github.com/applike/wp-lever/releases the 1.0.1 version is the one which is similar to this pull request

note: you'll have to repackage the zip file the folder should not include the version, when you upload it to wordpress

**Comment by obiPlabon** [comment]
Hello @netsi what is your wp.org username? I'd like to add you as committer as you've added lots of functionality and it seems your have more ideas to implement.

Thanks

**Comment by netsi** [comment]
Hey @obiPlabon I don't have wp.org account, and there is not need for mention 😄

**Pull request merged**
